paths:
  /get_horoscope:
    post:
      summary: 查询本命星盘
      description: 根据出生年月日、时间、地点查询星体落座信息
      operationId: getHoroscope
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                birth_date:
                  type: string
                  example: "1994-02-07"
                  description: 出生日期，格式为 yyyy-mm-dd
                birth_time:
                  type: string
                  example: "19:20"
                  description: 出生时间，格式为 HH:mm
                birth_place:
                  type: string
                  example: "深圳"
                  description: 出生地点
      responses:
        "200":
          description: 成功返回星盘信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  birth_date:
                    type: string
                  birth_time:
                    type: string
                  birth_place:
                    type: string
                  planets:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        星座序號:
                          type: integer
                        星座名稱:
                          type: string
                        度數:
                          type: number
                        全度數:
                          type: number
                  zodiac_table:
                    type: object
